export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const SET_MOVIE = 'SET_MOVIE';

export const GET_MOVIES_BY_PAGE = 'GET_MOVIES_BY_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const GET_MOVIES_COUNT = 'GET_MOVIES_COUNT';
export const SET_MOVIES_COUNT = 'SET_MOVIES_COUNT';

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';

export const SEARCH_INPUT_CHANGED = 'SEARCH_INPUT_CHANGED';


export const GET_COMMENTS_BY_MOVIE = 'GET_COMMENTS_BY_MOVIE';
export const POST_COMMENT = 'POST_COMMENT';
export const PUT_COMMENTS = 'PUT_COMMENTS';
export const PUT_NEW_COMMENT = 'PUT_NEW_COMMENT';

export const INCREASE_MOVIE_VISITS = 'INCREASE_MOVIE_VISITS';


export const GET_ALL_GENRES = 'GET_ALL_GENRES';
export const PUT_GENRES = 'PUT_GENRES';
export const PUT_SELECTED_GENRE = 'PUT_SELECTED_GENRE';
export const DELETE_SELECTED_GENRE = 'DELETE_SELECTED_GENRE';

